name: Java CI with Gradle

on:
  push:
    branches: [ master ]
    tags:
      - "v*"
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [ 8, 17 ]
      fail-fast: true

    steps:
    - name: 检出代码
      uses: actions/checkout@v4

    - name: 设置 JDK ${{ matrix.java-version }}
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: ${{ matrix.java-version }}
        cache: 'gradle'

    - name: 赋予 gradlew 可执行权限
      run: chmod +x gradlew

    - name: 构建项目
      run: ./gradlew clean build --stacktrace

    - name: 上传构建产物 (Artifacts)
      uses: actions/upload-artifact@v4
      with:
        name: ServerUtils-${{ matrix.java-version }}
        path: build/libs/*.jar

    - name: 发布 Release 
      if: startsWith(github.ref, 'refs/tags/v')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        VERSION=${GITHUB_REF#refs/tags/}
        gh release create "$VERSION" build/libs/*.jar --title "Release $VERSION" --notes "自动发布的版本 $VERSION"
