name: Java CI with Gradle

on:
  push:
    branches: [ master ]
    tags:
      - "v*"
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [ 8, 17 ]
      fail-fast: true

    steps:
    - name: 检出代码
      uses: actions/checkout@v4

    - name: 设置 JDK ${{ matrix.java-version }}
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: ${{ matrix.java-version }}
        cache: 'gradle'

    - name: 赋予 gradlew 可执行权限
      run: chmod +x gradlew

    - name: 构建 Bukkit
      run: ./gradlew -p Bukkit clean build --stacktrace

    - name: 构建 Bungee
      run: ./gradlew -p Bungee clean build --stacktrace

    - name: 构建 Velocity
      run: ./gradlew -p Velocity clean build --stacktrace

    # 上传构建产物 (Artifacts)
    - name: 上传 Bukkit 产物
      uses: actions/upload-artifact@v4
      with:
        name: ServerUtils-Bukkit
        path: Bukkit/build/libs/*.jar

    - name: 上传 Bungee 产物
      uses: actions/upload-artifact@v4
      with:
        name: ServerUtils-Bungee
        path: Bungee/build/libs/*.jar

    - name: 上传 Velocity 产物
      uses: actions/upload-artifact@v4
      with:
        name: ServerUtils-Velocity
        path: Velocity/build/libs/*.jar

